spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/openfeign_db
    username: postgres
    password: 2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081